name: Actuarial Platform Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      r-service:
        image: rocker/r-ver:4.3.0
        ports:
          - 6311:6311

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scipy
        pip install unittest2 rpy2

    - name: Set up R environment
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        R -e "install.packages('demography', repos='https://cloud.r-project.org')"
        R -e "install.packages('StMoMo', repos='https://cloud.r-project.org')"

    - name: Run tests
      run: |
        # 创建测试数据目录
        mkdir -p data
        
        # 运行测试脚本
        python test_actuarial_platform.py
        
        # 检查测试结果
        if [ -f test_report.json ]; then
          echo "测试报告:"
          cat test_report.json
          
          # 检查测试是否全部通过
          if jq -e '.success == true' test_report.json; then
            echo "所有测试通过 ✅"
          else
            echo "测试失败 ❌"
            exit 1
          fi
        else
          echo "未找到测试报告"
          exit 1
        fi

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: actuarial-test-report
        path: |
          test_report.json
