name: Test Actuarial Platform

on:
  push:
    branches: [main]  # 推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 安装 R 依赖（解决 demography 包问题）
      - name: 安装 R 及依赖
        run: |
          sudo apt-get update -y
          sudo apt-get install -y r-base r-base-dev libgfortran5 libcurl4-openssl-dev
          mkdir -p ~/R_libs
          R -e 'install.packages("demography", repos = "https://cran.rstudio.com/", lib = "~/R_libs")'
          echo "R_LIBS_USER=~/R_libs" >> $GITHUB_ENV

      # 安装 Python 依赖
      - name: 安装 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装 Python 依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # 读取根目录的 requirements.txt

      # 执行测试文件
      - name: 执行测试文件
        run: |
          pytest test_actuarial_platform.py -v  # 测试文件在根目录
