name: Test Actuarial Platform

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 新增：构建并运行 Docker 容器，替换原来的 R 依赖安装步骤
      - name: 构建并运行测试容器
        run: |
          # 构建 Docker 镜像（会安装 R 和 Python 依赖）
          docker build -t actuarial-test .
          # 运行容器并执行测试
          docker run actuarial-test

      # 保留：安装 Python 依赖
      - name: 安装 Python 依赖
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 保留：执行测试
      - name: 执行测试文件
        run: |
          pytest test_actuarial_platform.py -v
