name: Test Actuarial Platform

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 设置 R 环境
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: 安装 R 包
        run: |
          Rscript -e 'install.packages("demography", repos="https://cloud.r-project.org")'

      - name: 构建并运行测试容器
        run: |
          docker build -t actuarial-test .
          docker run --rm actuarial-test

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装 Python 依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 pytest 测试
        run: |
          pytest test_actuarial_platform.py -v
