name: Run HMD Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("HMDHFDplus", "readr", "dplyr", "renv"), repos = "https://cloud.r-project.org")'
          # 如果使用 renv，取消下面这行注释
          # Rscript -e 'renv::restore()'

      - name: Run R script
        env:
          HMD_USERNAME: ${{ secrets.HMD_USERNAME }}
          HMD_PASSWORD: ${{ secrets.HMD_PASSWORD }}
        run: |
          Rscript test/test4/scripts/fetch_hmd_data.R
